// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"about-background opacity-90 flex justify-center h-screen items-center bg-[#989898]\"><div class=\"about-section space-y-8 backdrop-blur-[10px] rounded-[1.75em] p-[30px] bg-[rgba(255,255,255,0.45)] h-[90] w-1/2\" dir=\"rtl\"><h1 class=\"text-center text-5xl \">عن المعجم الحويط</h1><h3 class=\"text-3xl\">ما هو؟</h3><p>معجم المصطلحات الحويط هو محاولة لتجميع المصطلحات المختلفة التي تندرج تحت مجموعة معينة من المواضيع أو المجالات، وذلك لتوفير مصدر شامل يتيح للمستخدمين الوصول بسهولة إلى معاني المصطلحات وتفسيرها بشكل دقيق. هو أقرب إلى مصدر يجمع المحاولات السابقة ويُلمّ الشتات الموجود في اللغة العربية في المجال العلمي، ليكون مرجعًا موثوقًا يعكس تنظيم وتوحيد المصطلحات في المجالات المتخصصة. كما يضم أيضًا استخدامات المصطلحات كما تظهر في بعض الشركات الكبيرة مثل آبل وموزيلا، التي ساهمت في تشكيل وتحديد شكل هذه المصطلحات. يهدف المعجم إلى تسهيل البحث والفهم للمختصين والباحثين في تلك المجالات، مما يسهم في تعزيز تبادل المعرفة والفهم المشترك بين المتحدثين باللغة العربية.</p><h3 class=\"text-3xl\">اللغات المدعومة</h3><div class=\"flex items-center justify-evenly gap-2 space-x-6 p-4\"><span class=\"text-lg bg-[#0e2a47] text-white py-2 px-4 rounded-full\">إنجليزي</span> <span class=\"text-lg bg-[#0e2a47] text-white py-2 px-4 rounded-full\">فرنسي</span> <span class=\"text-lg bg-[#0e2a47] text-white py-2 px-4 rounded-full\">ألماني</span> <span class=\"text-lg bg-[#0e2a47] text-white py-2 px-4 rounded-full\">العربية</span></div><p>يحاول المعجم الحويط العثور على مصادر تحوي الأربع لغات التي اعتبرها مربوطة أو مؤثرة على اللغة العربية في السياق العلمي، ولكن في الأساس يشترط وجود الإنجليزية نظرًا لتأثيرها الحالي على المجالات العلمية، خصوصًا البرمجية والنفسية. يعمل المعجم على توثيق هذه اللغات من خلال قواميس متعددة اللغات والمراجع العلمية التي تدمج بينها</p><h3 class=\"text-3xl\">المجالات</h3></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = template().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<style>\n    .about-background{\n        background-image:  radial-gradient(#989898 0.75px, transparent 0.75px), radial-gradient(#989898 0.75px, #ffffff 0.75px);\n        background-size: 30px 30px;\n        background-position: 0 0,15px 15px;\n    }\n    .about-section{\n        box-shadow: 0 0 20px -5px rgba(0, 0, 0, 0.3), 0 0 12px -7px rgba(0, 0, 0, 0.2);\n    }\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
