// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Search() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"h-screen flex justify-center\"><div class=\"h-[33vh] flex flex-col items-center justify-evenly w-screen search-section\"><h1 class=\"text-6xl\">المعجم الحويط</h1><div class=\"search-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SearchForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><p class=\"text-xl mt-2\">معجم هدفه لم شتات المصطلحات في المجالات العلمية</p></div></div><style>\n    .search-section {\n        background-color: #989898;\n        opacity: 0.9;\n        background-image: radial-gradient(#989898 0.75px, transparent 0.75px),\n            radial-gradient(#989898 0.75px, #ffffff 0.75px);\n        background-size: 30px 30px;\n        background-position: 0 0, 15px 15px;\n    }\n\n    .search-container {\n        width: 100%;\n        max-width: 800px; /* Maximum width of 600px */\n        margin: 0 auto;   /* Center it horizontally */\n        padding: 0 15px;  /* Optional: adds a little padding for responsiveness */\n    }\n\n    /* For screen sizes smaller than 768px, let it take up most of the width */\n    @media (max-width: 768px) {\n        .search-container {\n            width: 90%; /* Adjust the width to take up most of the screen */\n        }\n    }\n\n</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
